# Generated by Django 5.2.5 on 2025-08-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[("manager", "Manager"), ("default_user", "Default User")],
                default="default_user",
                max_length=20,
            ),
        ),
    ]
